### PR TITLE
✨ Added a new `large-excerpt` class which allows for 10 lines of text

### PR DESCRIPTION
**Pull request by ashleytowner**
# Pull Request Overview
Adds a `large-excerpt` class which limits a block of text to 10 lines.

Based on [this ticket](https://www.notion.so/greenpeaceaustraliapacific/P4-Remove-Line-clamps-on-excerpts-6c45d5963f5d41daac27d65ba25e477a?pvs=4)

## 🏁 PR Checklist

Reviewer checklist:
- [ ] ✨ This PR includes new user-facing feature and/or settings
- [ ] 📝 Documentation for new features/settings are in PR description (to go to wiki or Coral docs) 

Contributor checklist:
- [x] Reference a GitHub issue, Jira ticket, or Notion card in the description 💯
- [ ] 📝 Update the CHANGELOG.md (Put under `[Unreleased]`). Include link to this PR.
- [ ] 📝 Add JSDoc code documentation
- [ ] 🏷 Add flow types. (If needed.)
- [ ] ✅ Add unit tests (`*.test.js`) and/or Cypress Tests.
- [ ] 📖 Create Storybook stories. (For any applicable Components.)
- [ ] 📸 Update snapshots.  Run `yarn test:watch`, press 'a' for "all tests", and "u" to update snaps if needed.
- [ ] Run tests (`yarn test` and `yarn flow`) and clean up any errors 🚀
- [x] Select 1-2 Reviewers
- [x] Feel good about yourself, you're doing great! 🥳

### CODE REVIEW

**Review by techieshark — APPROVED** [review]
LGTM but might be good to update PR body or notion or something so one side effect of this PR is we have a good explanation of how we make use of this new class.

**Comment by ashleytowner** [comment]
@techieshark I think the ticket explains the use-case of the class pretty well? What do you think needs expanding upon?

**Comment by techieshark** [comment]
@ashleytowner yeah the PR does what the PR says (add new class) but the ticket is talking about fixing an existing page, which used an existing (different) class. So I'm curious if the person who raised that ticket knows that they need to change something (what?) to actually use this new class.

> I would like this either set to 5 to allow more of the excerpt to be shown. Or we can create a CSS class i.e .full-excerpt which allows for the full excerpt to be shown on Bio pages.

Like I am curious if the ticket was a bit underspecified and perhaps an existing template (??) needs to be modified next, so this class is actually used.

**Comment by ashleytowner** [comment]
@techieshark Ah yes, Kara is the one who raised the ticket, I believe, and has only requested that the class be available for use. 

Happy to ask Kara to write something up about the class & where it needs to be used though.

**Comment by techieshark** [comment]
@ashleytowner that'd be great

**Pull request merged**
