### PR TITLE
Apply narrow-container class on post types

### PR DESCRIPTION
**Pull request by karabishopgreenpeace**
The post containers were looking a bit inconsistent, so i've made them all the same width as the single.twig file using the narrow-container class.

# Pull Request Overview
I have re-applied the narrow-container class to the custom post-type templates. This style was used in the original single.css file which these were duplicated from, so is just winding back to the standard.

# 📷 Screenshots

What it looked like without narrow-container class
Screenshot 2024-03-01 at 2 43 18 pm

What it looks like now
Screenshot 2024-03-01 at 2 42 37 pm

## 🤨 Any Issues or Questions?
No

## 🏁 PR Checklist

Reviewer checklist:
- [ ] ✨ This PR includes new user-facing feature and/or settings
- [ ] 📝 Documentation for new features/settings are in PR description (to go to wiki or Coral docs) 

Contributor checklist:
- [ ] Reference a GitHub issue, Jira ticket, or Notion card in the description 💯
- [ ] 📝 Update the CHANGELOG.md (Put under `[Unreleased]`). Include link to this PR.
- [ ] 📝 Add JSDoc code documentation
- [ ] 🏷 Add flow types. (If needed.)
- [ ] ✅ Add unit tests (`*.test.js`) and/or Cypress Tests.
- [ ] 📖 Create Storybook stories. (For any applicable Components.)
- [ ] 📸 Update snapshots.  Run `yarn test:watch`, press 'a' for "all tests", and "u" to update snaps if needed.
- [ ] Run tests (`yarn test` and `yarn flow`) and clean up any errors 🚀
- [x] Select 1-2 Reviewers
- [x] Feel good about yourself, you're doing great! 🥳

### CODE REVIEW

**Comment by ashleytowner** [comment]
These screenshots look *very* different, notably the following:

| before | after | explanation |
|:-:|:-:|:--|
|image|image|Wording changed|
|image|image|profile picture changed
|image|image|Two titles became one

These changes don't really seem to be reflected in the code changes of this PR. What's going on here?

**Comment by karabishopgreenpeace** [comment]
@ashleytowner the before is a screenshot on the prod site (real content). The second is just dummy content on my local site (using the same template).

**Comment by ashleytowner** [comment]
@karabishopgreenpeace could you please add screenshots of the same content, before & after the changes?

**Comment by karabishopgreenpeace** [comment]
Before:
Screenshot 2024-03-08 at 11 17 24 am

After:
Screenshot 2024-03-08 at 11 17 07 am

**Review by ashleytowner — APPROVED** [review]
LGTM. Feel free to merge @karabishopgreenpeace

**Pull request merged**
