### PR TITLE
Reduce line-height in buttons

### PR DESCRIPTION
**Pull request by ashleytowner**
# Pull Request Overview
This sets button line height to be more reasonable, because before it was very big. Reducing the line height meant that the spacing between the text and the edge of the button decreased, so I've increased padding to get that back to what it was. 

Fixes [this ticket](https://www.notion.so/greenpeaceaustraliapacific/P4-Line-height-on-buttons-054cbfe964cc4289868df05e2bfeb112?pvs=4)

# 📷 Screenshots

| Before | After |
|:-:|:-:|
|image|image|

# QA / Test steps

1. Create a blank post
2. Add a 2 column layout
3. Inside one column, add a button, with long text like "i am a button with some really long text it goes on an on I swear"
5. Observe the before/after from `main` to `feature/fix-button-line-height` branches

### CODE REVIEW

**Review by techieshark — COMMENTED** [review]
This does seem to address the issue with line-height causing large and potentially unexpected vertical gaps between lines of text in multi-line buttons.

That said, two thoughts...

1. if people have such long buttons maybe they should re-think what they're doing.
2. More pertinent here, I'd suggest if we want to fix this we do it 'upstream' in the master theme, rather than this child theme. So my suggestion would be to basically take this change and propose it in https://github.com/greenpeace/planet4-master-theme/

More thoughts/review -
  
The initial Button style implementation was here - https://jira.greenpeace.org/browse/PLANET-4152 (and in case you don’t have access, the key point is it links to this other doc): https://p4-designsystem.greenpeace.org/05f6e9516/p/77fb76-buttons/b/6663d1

That original doc says:

> As a general rule buttons have an internal padding of 14px (Top & bottom).

> If the button text is long then the same internal padding of 14px is applied left & right. Padding is generated via line height. Default buttons (sm) have a 3rem (48px) line height. 

With this in mind, the `button-padding` of `1rem` would translate to `16px` (unless my poking around in the browser is giving me the wrong info about what the root element size is).

Also, am curious how we landed on the line-height of `1.3em`? Assuming the goal was just to set this back to the 'normal' value (effectively unsetting it), would we want to use either `normal` or `1.2`? See https://developer.mozilla.org/en-US/docs/Web/CSS/line-height

**Comment by ashleytowner** [comment]
@techieshark 

> if people have such long buttons maybe they should re-think what they're doing.

Possibly, but if they decide it is important then I still think the buttons should look good.

> More pertinent here, I'd suggest if we want to fix this we do it 'upstream' in the master theme

We can do that, but I'd like to also get it fixed here first, as I suspect it will be a much longer process to get it merged into the upstream. 

> With this in mind, the `button-padding` of `1rem` would translate to `16px`
> Also, am curious how we landed on the line-height of `1.3em`?

The answer to both of these is that I wasn't sure what it *should* be set to, as there wasn't anything in the acceptance criteria about it and I wasn't aware that the P4 design systems documentation existed, so I just played around with different values for each & picked something I thought looked nice.

**Comment by techieshark** [comment]
>  if they decide it is important then I still think the buttons should look good.

Fair enough, agreed. As a sidenote, from a design perspective, perhaps we need to think of how we can help people use buttons appropriately. Something like this perhaps - https://designsystem.digital.gov/components/button/#button-guidance

> We can do that, but I'd like to also get it fixed here first, as I suspect it will be a much longer process to get it merged into the upstream.

That's logical for sure, but essentially introduces technical debt and I'm not sure that anyone will be clamouring for that debt to get paid off. So I would just ask what the plan is to actually get that done?

**Comment by ashleytowner** [comment]
> Fair enough, agreed. As a sidenote, from a design perspective, perhaps we need to think of how we can help people use buttons appropriately. Something like this perhaps - https://designsystem.digital.gov/components/button/#button-guidance

Is that link not enough? By the looks of it it *seems* like enough, it's just a case of making sure people are aware of it and actually consult it.

 

> So I would just ask what the plan is to actually get that done?

I don't know. I don't think I have a good enough understanding of how it would even work to get it fixed upstream now to weigh in on this meaningfully

**Comment by techieshark** [comment]
@ashleytowner as a starting point, can you file a bug report here and in that, link to this PR to refer them to the suggested fix? That may be enough to get the ball rolling at least.  

https://planet4.greenpeace.org/contribute/report-bugs/

**Comment by ashleytowner** [comment]
> @ashleytowner as a starting point, can you file a bug report here and in that, link to this PR to refer them to the suggested fix? That may be enough to get the ball rolling at least.
> 
> https://planet4.greenpeace.org/contribute/report-bugs/

Done

**Review by techieshark — CHANGES_REQUESTED** [review]
@ashleytowner thanks for filing that issue with upstream.

As for these specific changes -

1. Line height of 1.3 looks good. It's a tad bigger than `normal` but I agree that it looks good and it does feel more appropriate for a button.

2. For `--button--padding` what do you feel about trying to track closely with the published style system? So use `12px 32px` for the value.

https://p4-designsystem.greenpeace.org/05f6e9516/p/77fb76-buttons/b/6663d1/i/228255480

image

**Comment by ashleytowner** [comment]
@techieshark I have changed the padding to match the 12 / 32px value, although I have used rems instead as they play nicer with a11y modifications like changing the root font size.

**Review by techieshark — APPROVED** [review]
>  I have used rems instead as they play nicer with a11y modifications like changing the root font size

Cool cool, I was hoping you'd do that :)

**Pull request merged**
