### PR TITLE
🐛 fix: Content sits under unscrolled header & icons are correct colour

### PR DESCRIPTION
**Pull request by ashleytowner**
# Pull Request Overview
This PR makes it so that the content on the homepage sits beneath the header, even on mobile. It also makes the icons for search & the hamburger menu white instead of black, as is the standard on desktop. 

Fixes [this ticket](https://www.notion.so/greenpeaceaustraliapacific/P4-White-space-under-navigation-on-mobile-eae900155c024d00a1e77810a291b2ed?pvs=4)

# 📷 Screenshots
image
image

### CODE REVIEW

**Review by techieshark — CHANGES_REQUESTED** [review]
@ashleytowner can you please rebase and push again? Looks like we have some conflicts. 

Possibly related but when I look at this on my machine I see some odd breakpoint happening ("odd" meaning the logo and the nav bar elements split to be on two lines around 992px):

image

**Review by techieshark — CHANGES_REQUESTED** [review]
Nice and simple - love that! 

One nit - I noticed the search icon contrast disappears when actually in use. 

How it's designed to look (p4 default):
image

How it looks with this change (white icon on grey background, not enough contrast):
image



---

There are two other issues I picked up on while reviewing this. Do you want to make cards or do you know if we already have cards for them? 

1. Something's up with it at small sizes?

This looks good (international): https://www.greenpeace.org/international/ 
image

This looks off (note search icon has wrapped):
image

I think it's probably caused by my own sloppy work with the header (the logo gets too big and the smallest screen sizes aren't expecting it).


2. The search bar is somewhat unsable. Main issue is the **font** is white on white background.

image

**Comment by ashleytowner** [comment]
> Do you want to make cards or do you know if we already have cards for them?

@techieshark I don't think we have cards for these already, no. Could you make them?

**Comment by techieshark** [comment]
@ashleytowner sure, I can do that

**Comment by techieshark** [comment]
Noting that we have separate notion cards for the two other issues, so we may be able to proceed with this for now.

**Comment by techieshark** [comment]
just fix the contrast (white mag glass icon on grey background)

**Comment by ashleytowner** [comment]
@techieshark I've made the background dark now in order to improve the contrast. 
image

**Review by techieshark — APPROVED** [review]
LGTM @ashleytowner thanks!

**Pull request merged**
