### PR TITLE
Feature/add long bio to profile page

### PR DESCRIPTION
**Pull request by karabishopgreenpeace**
# Pull Request Overview

The current author profiles in P4 are pretty limited. They don't allow links or any formatted content. I would like to have detailed profile pages for our campaigners and web authors.

I have included Advanced Custom Fields (ACF) onto the user profiles to allow more flexibility. Including a wysiwyg editor, field for job role, LinkedIn url (optional) and bio image field.

**To get them to work I:**

• Registered the ACF Long Bio Fields in functions.php
• Fetched the ACF Bio Fields in author.php
• Outputted the ACF Bio Fields in author.twig using custom classes so we can style them.
• It worked fine on my local environment, so I've swapped the ACF field keys to match the dev environment.

# 📷 Screenshots
Screenshot 2023-12-13 at 7 25 17 pm

## 🤨 Any Issues or Questions?
• I didn't have any luck with the image upload. The buttons on the user profiles don't open the image library. I might need someone to have a look at this for me. For now though, the profiles use Google Avatars. In the future, I'd like authors to be able to choose their own photos.

• When the site gets synced from dev to prod, will it sync the ACF field (ids)? or will we need to update these before pushing them to prod?

Let me know if you have any more Qs.

## 🏁 PR Checklist

Reviewer checklist:
- [ ] ✨ This PR includes new user-facing feature and/or settings
- [ ] 📝 Documentation for new features/settings are in PR description (to go to wiki or Coral docs) 

Contributor checklist:
- [ ] Reference a GitHub issue, Jira ticket, or Notion card in the description 💯
- [ ] 📝 Update the CHANGELOG.md (Put under `[Unreleased]`). Include link to this PR.
- [ ] 📝 Add JSDoc code documentation
- [ ] 🏷 Add flow types. (If needed.)
- [ ] ✅ Add unit tests (`*.test.js`) and/or Cypress Tests.
- [ ] 📖 Create Storybook stories. (For any applicable Components.)
- [ ] 📸 Update snapshots.  Run `yarn test:watch`, press 'a' for "all tests", and "u" to update snaps if needed.
- [ ] Run tests (`yarn test` and `yarn flow`) and clean up any errors 🚀
- [ ] Select 1-2 Reviewers
- [x] Feel good about yourself, you're doing great! 🥳

### CODE REVIEW

**Comment by ShoryuDZ** [comment]
Hey @karabishopgreenpeace, can I just get some quick instructions on where to go/look to test this? I've had a look across the code which looks alright, just want to be able to see it working locally. Thanks!

**Comment by karabishopgreenpeace** [comment]
It should show on the Author bio pages (see https://www-dev.greenpeace.org/australiapacific/author/kbishop/).

Under the short description, there should be a longer bio. The fields are populated via ACF fields on the user page.

Screenshot 2024-01-15 at 8 57 26 pm

**Comment by ShoryuDZ** [comment]
Hey @karabishopgreenpeace - apologies, I should've been clearer with my instructions. I'm looking to test this locally, not on a dev/staging site - I've tried playing around with creating a few Editor and Author profiles but I haven't seen the option for "Editor Profile" come up at all (so theres no way I can add a long bio to anyone to witness it working locally). Do you think you'd be able to give me some instructions on how I can see these options? Or if you'd prefer to walk through it with me on call when you're back that would be great.

**Review by techieshark — CHANGES_REQUESTED** [review]
Hi @karabishopgreenpeace thanks for this! 

So that it makes it easier to understand and maintain in the future, what would be amazing is if you and Shoryu could do the following:

1. Make new branch
2. Copy in any base file that you're about to modify (like the author.twig file). Do not modify the file.
3. Make a commit that just notes that you've copied in the file from the parent theme. 
4. After having committed the initial file, you can copy over the same file from this here branch (in other words, you'll be effectively applying your customisations). Also copy in functions.php from your branch.
5. Commit those two sets of changes - to author.twig and functions.php - in an atomic commit.
6. Push the new branch and make a new PR from it.

Then I'm happy to review again hopefully later today. Thanks!

**Comment by techieshark** [comment]
Closing as #35 replaces this; thanks so much for getting this started Kara! :)

**Pull request closed without merging**
