### PR TITLE
Feature/revert image float fix

### PR DESCRIPTION
**Pull request by ashleytowner**
The last PR I made reverted the changes we made to these classes, but it should have just removed them altogether because they have been properly implemented upstream in P4. 

I've tested this change and it appears to work locally. This fixes [this ticket](https://www.notion.so/greenpeaceaustraliapacific/P4-Float-images-correctly-fixed-UPSTREAM-revert-in-ours-now-bf84bb62d9ff45b6867b2c0c49bcd0a8?pvs=4)

### CODE REVIEW

**Comment by techieshark** [comment]
@ashleytowner looks like you've got conflicts to resolve, did you want to do that before a review?

**Review by techieshark — APPROVED** [review]
LGTM

**Comment by ashleytowner** [comment]
@techieshark merge errors fixed

**Review by techieshark — APPROVED** [review]
lgtm

**Pull request merged**
